version: "3"

services:
  app:
    env_file: .env
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ".:/usr/app"

  db:
    image: postgres:12.4-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "dbdata:/var/lib/postgresql/data/pgdata"

volumes:
  dbdata: